<!DOCTYPE html>
<html>
<head>
    <title>Joseph MUHIRE PHP</title>
</head>
<body>
    <h1>Joseph MUHIRE PHP</h1>

    <pre>
    JJJJ
       J
       J
       J
    J  J
    JJJ
    </pre>

    <p>SHA256 of my name:</p>
    <P>
        <?php
        // I am using this to show the SHA256 hash of my name
            echo hash('sha256', 'Joseph MUHIRE');
        ?>
    </p>
</body>
</html>
